# Performing EDA and predicting penguins species by using Logistic Regression.

* Multiclass Classification.

In [147]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings # ignore warnings
warnings.filterwarnings("ignore")

In [188]:
df = pd.read_csv('penguins.csv')
df.tail()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [149]:
df.columns # it will give name of columns of dataset

Index(['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex'],
      dtype='str')

In [150]:
df.duplicated().sum() # data have no duplicate values in it.

np.int64(0)

In [151]:
df.drop(columns= ['island','sex'],inplace = True)
df.head()

  species  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
0  Adelie            39.1           18.7              181.0       3750.0
1  Adelie            39.5           17.4              186.0       3800.0
2  Adelie            40.3           18.0              195.0       3250.0
3  Adelie             NaN            NaN                NaN          NaN
4  Adelie            36.7           19.3              193.0       3450.0

* changing body mass into kilograms(kg).

In [195]:
df['body_mass_kg'] = df['body_mass_g']/1000
df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,body_mass_kg
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE,3.75
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE,3.80
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE,3.25
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE,3.45

In [153]:
df.drop(columns= ['body_mass_g'],inplace =True)
df.head()

  species  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_kg
0  Adelie            39.1           18.7              181.0          3.75
1  Adelie            39.5           17.4              186.0          3.80
2  Adelie            40.3           18.0              195.0          3.25
3  Adelie             NaN            NaN                NaN           NaN
4  Adelie            36.7           19.3              193.0          3.45

In [154]:
df.describe()

       bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_kg
count      342.000000     342.000000         342.000000    342.000000
mean        43.921930      17.151170         200.915205      4.201754
std          5.459584       1.974793          14.061714      0.801955
min         32.100000      13.100000         172.000000      2.700000
25%         39.225000      15.600000         190.000000      3.550000
50%         44.450000      17.300000         197.000000      4.050000
75%         48.500000      18.700000         213.000000      4.750000
max         59.600000      21.500000         231.000000      6.300000

In [155]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    str
 1   bill_length_mm     342 non-null    float64
 2   bill_depth_mm      342 non-null    float64
 3   flipper_length_mm  342 non-null    float64
 4   body_mass_kg       342 non-null    float64
dtypes: float64(4), str(1)
memory usage: 13.6 KB

In [156]:
df.isnull().sum()

species              0
bill_length_mm       2
bill_depth_mm        2
flipper_length_mm    2
body_mass_kg         2
dtype: int64

* filing null(int/float) values with their mean values

In [157]:
df['bill_depth_mm'] = df['bill_depth_mm'].fillna(df['bill_depth_mm'].mean())
df['bill_depth_mm'].isnull().sum()

np.int64(0)

In [158]:
df['bill_length_mm'] = df['bill_length_mm'].fillna(df['bill_length_mm'].mean())
df['flipper_length_mm'] = df['flipper_length_mm'].fillna(df['flipper_length_mm'].mean())
df['body_mass_kg'] = df['body_mass_kg'].fillna(df['body_mass_kg'].mean())

In [159]:
df.isnull().sum()

species              0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_kg         0
dtype: int64

# now the data is cleaned

In [160]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    str
 1   bill_length_mm     344 non-null    float64
 2   bill_depth_mm      344 non-null    float64
 3   flipper_length_mm  344 non-null    float64
 4   body_mass_kg       344 non-null    float64
dtypes: float64(4), str(1)
memory usage: 13.6 KB

In [161]:
df.columns

Index(['species', 'bill_length_mm', 'bill_depth_mm', 'flipper_length_mm',
       'body_mass_kg'],
      dtype='str')

In [162]:
x = df[['bill_length_mm', 'bill_depth_mm','flipper_length_mm','body_mass_kg']]
y = df['species']

In [163]:
x

     bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_kg
0          39.10000       18.70000         181.000000      3.750000
1          39.50000       17.40000         186.000000      3.800000
2          40.30000       18.00000         195.000000      3.250000
3          43.92193       17.15117         200.915205      4.201754
4          36.70000       19.30000         193.000000      3.450000
..              ...            ...                ...           ...
339        43.92193       17.15117         200.915205      4.201754
340        46.80000       14.30000         215.000000      4.850000
341        50.40000       15.70000         222.000000      5.750000
342        45.20000       14.80000         212.000000      5.200000
343        49.90000       16.10000         213.000000      5.400000

[344 rows x 4 columns]

In [164]:
y

0      Adelie
1      Adelie
2      Adelie
3      Adelie
4      Adelie
        ...
339    Gentoo
340    Gentoo
341    Gentoo
342    Gentoo
343    Gentoo
Name: species, Length: 344, dtype: str

* transforming y feature into 0,1,2 format

In [165]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [166]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [167]:
from sklearn.model_selection import train_test_split

In [168]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=23)

In [169]:
from sklearn.linear_model import LogisticRegression

In [170]:
model = LogisticRegression()

In [171]:
model.fit(x_train,y_train)

LogisticRegression()

In [172]:
y_test

array([0, 0, 0, 1, 2, 2, 1, 1, 0, 2, 2, 2, 2, 2, 1, 2, 0, 2, 0, 0, 1, 0,
       2, 2, 0, 0, 0, 2, 0, 1, 0, 2, 2, 0, 0, 2, 2, 2, 2, 0, 1, 0, 2, 0,
       0, 2, 1, 2, 1, 2, 0, 2, 2, 2, 0, 1, 0, 1, 2, 0, 2, 2, 0, 1, 2, 2,
       2, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 0, 2, 0, 0, 2, 1, 0, 1, 2, 0, 0,
       1, 0, 2, 0, 0, 2, 2, 2, 0, 0, 0, 1, 2, 0, 2, 0])

In [173]:
y_pred = model.predict(x_test)
y_pred

array([0, 0, 0, 1, 2, 2, 1, 0, 0, 2, 2, 2, 0, 2, 1, 2, 0, 2, 0, 0, 1, 0,
       2, 2, 0, 0, 0, 2, 0, 1, 0, 2, 2, 0, 0, 2, 2, 2, 2, 0, 1, 1, 2, 0,
       0, 2, 1, 2, 1, 2, 0, 2, 2, 2, 0, 1, 0, 1, 2, 0, 2, 2, 0, 1, 2, 2,
       2, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 0, 2, 0, 0, 2, 1, 0, 1, 2, 0, 0,
       1, 0, 2, 0, 0, 2, 2, 2, 0, 0, 0, 1, 2, 0, 2, 0])

In [174]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.9711538461538461
[[42  1  0]
 [ 1 15  0]
 [ 1  0 44]]

# now predict by giving some random values to it.

In [189]:
result = model.predict([[45,14,212,65]])
if result[0] == 0:
    print('Penguin belongs to Adelie species')
elif result[0] == 1:
    print('Penguin belongs to Chinstrap Species')
else:
    print("Penguin belongs to Gentoo species")

Penguin belongs to Gentoo species

In [197]:
model.predict([[50,17,200,3.5]])

array([1])